name: spt_ci_cd_workflow

on:
    push:
        branches: ['main', 'feature/*']
    pull_request:
        branches: ['main']
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build API
              run: dotnet build --no-restore
            - name: Run Unit Tests
              run: dotnet test --no-build --verbosity normal

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                   node-version: '16.x'
            - run: cd ./sprintplanningtool
            - name: Install dependencies
              run: npm i
            - name: NPM run build
              run: npm run build --if-present
            - run: npm test
    
            
