name: spt_ci_cd_workflow

on:
    push:
        branches: ['main', 'feature/*']
    pull_request:
        branches: ['main']

jobs:
    build_backend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build API
              run: dotnet build --no-restore
            - name: Unit Tests
              run: dotnet test --no-build --verbosity normal
    
    build_frontend:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [14.x, 16.x, 18.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: cd sprintplanningtool    
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test
            
