name: spt_ci_cd_workflow

on:
    push:
        branches: ['main', 'feature/*']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16.x'
            - run: cd sprintplanningtool
            - run: npm ci
            - run: npm run build --if-present
            
            # - name: Setup Node.js environment
            #   uses: actions/setup-node@v3.4.1
            #   with:
            #     node-version: 16.16.0
            # - name: npm install, run, log
            #   run: |
            #     trap logs 1 2 3 6

            #     npm install
            #     npm run
            #     npm run build

            #     logs()
            #     {
            #       cd /home/runner/.npm/_logs && cat "$(ls -rt | tail -n1)"
            #     }
                
