name: spt_ci_cd_workflow

on:
    push:
        branches: ['main', 'feature/*']
    pull_request:
        branches: ['main']

jobs:
    build(backend):
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build Backend
              run: dotnet build --no-restore
    tests:
        - name: Test
        - run: dotnet test --no-restore--verbosity-normal

    build(frontend):
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
              node-version: '16.x'
        - name: NPM clean install
        - run: cd sprintplanningtool
        - run: npm ci
        - name: Build Frontend
        - run: npm run build --if-present
